s390x: Re-add RawSockaddrUnix structure
The structure has been removed by commit c88ed9c5c9a ("update vendor") for
mips64, mips64_le, and s390x.

This leads to the following build error on s390x:

 $ make
 go build -tags "static_build  with_libvirt" -o runv .
 # github.com/hyperhq/runv/vendor/golang.org/x/sys/unix
 vendor/golang.org/x/sys/unix/syscall_unix.go:165: undefined: RawSockaddrVsock
 make: *** [build-runv] Error 2

So re-add the structure to fix the build error.

Signed-off-by: Michael Holzheu <holzheu@linux.vnet.ibm.com>